### ISSUE TITLE
Locations clash

### ISSUE THREAD

**Issue by lewispb** [lewispb/rubymap#48]
If two locations have the same address, such as London or Paris, then the coordinates will be the same and the locations will clash. Can we avoid this by..
- randomise the last digit of the coordinates slightly?
- add a unique constraint in the DB
- adjust duplicate coordinates very slightly in a consistent way

**Comment by z3ugma** [comment]
I noticed this too with a few Madison businesses that share an office. The last one on the seeds file seems to be the one that is preferentially displayed.
